services:
  - type: web
    name: shree-parth-academy
    runtime: image
    plan: free
    region: frankfurt
    buildCommand: |
      dotnet restore
      dotnet publish -c Release -o out
    startCommand: dotnet out/Shivakala.Web.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__Provider
        value: PostgreSql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
