// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Shivakala.Infrastructure.Data;

#nullable disable

namespace Shivakala.SqlServerMigrations.Migrations
{
    [DbContext(typeof(ShivakalaDbContext))]
    [Migration("20260609013000_AddHomeBannerAndStudentIdCardSupport")]
    partial class AddHomeBannerAndStudentIdCardSupport
    {
    }
}
